<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class PackageSeeder extends Seeder
{
    public function run(): void
    {
        $packages = [
            // PAKET BEASISWA S1 - Uang Saku
            [
                'name' => 'Paket Uang Saku - Basic',
                'slug' => 'paket-uang-saku-basic',
                'icon' => 'heroicon-o-chat-bubble-left-right',
                'category' => 's1',
                'price_min' => 1500000,
                'price_max' => 1500000,
                'description' => 'Social Media Management dengan 12 Konten per Bulan. Membantu 1 mahasiswa mendapatkan beasiswa berupa uang saku untuk kebutuhan pendidikan.',
                'features' => json_encode([
                    'Social Media Management',
                    '12 Konten per Bulan',
                    'Desain Konten Kreatif',
                    'Caption & Hashtag Strategy',
                    'Posting Schedule',
                    'Monthly Report',
                ]),
                'target_beneficiaries' => 1,
                'service_type' => 'Social Media Management',
                'is_active' => true,
                'is_featured' => false,
                'order' => 1,
            ],
            [
                'name' => 'Paket Uang Saku - Standard',
                'slug' => 'paket-uang-saku-standard',
                'icon' => 'heroicon-o-megaphone',
                'category' => 's1',
                'price_min' => 3000000,
                'price_max' => 3000000,
                'description' => 'Social Media Management dengan 20 Konten per Bulan. Membantu 2 mahasiswa mendapatkan beasiswa berupa uang saku untuk kebutuhan pendidikan.',
                'features' => json_encode([
                    'Social Media Management',
                    '20 Konten per Bulan',
                    'Desain Konten Premium',
                    'Caption & Hashtag Strategy',
                    'Posting Schedule Optimal',
                    'Engagement Monitoring',
                    'Monthly Performance Report',
                ]),
                'target_beneficiaries' => 2,
                'service_type' => 'Social Media Management',
                'is_active' => true,
                'is_featured' => true,
                'order' => 2,
            ],
            [
                'name' => 'Paket Uang Saku - Professional',
                'slug' => 'paket-uang-saku-professional',
                'icon' => 'heroicon-o-rocket-launch',
                'category' => 's1',
                'price_min' => 4000000,
                'price_max' => 4000000,
                'description' => 'Social Media Specialist: 20 Konten & 2 Campaign Marketing per Bulan. Membantu 3 mahasiswa mendapatkan beasiswa berupa uang saku untuk kebutuhan pendidikan.',
                'features' => json_encode([
                    'Social Media Specialist',
                    '20 Konten per Bulan',
                    '2 Campaign Marketing per Bulan',
                    'Desain Konten Premium',
                    'Content Strategy',
                    'Campaign Planning & Execution',
                    'Audience Targeting',
                    'Engagement Monitoring',
                    'Monthly Performance Report',
                ]),
                'target_beneficiaries' => 3,
                'service_type' => 'Social Media Marketing',
                'is_active' => true,
                'is_featured' => true,
                'order' => 3,
            ],
            [
                'name' => 'Paket Uang Saku - Enterprise',
                'slug' => 'paket-uang-saku-enterprise',
                'icon' => 'heroicon-o-fire',
                'category' => 's1',
                'price_min' => 5000000,
                'price_max' => 5000000,
                'description' => 'Social Media Specialist: 30 Konten & 4 Campaign Marketing per Bulan. Membantu 4 mahasiswa mendapatkan beasiswa berupa uang saku untuk kebutuhan pendidikan.',
                'features' => json_encode([
                    'Social Media Specialist',
                    '30 Konten per Bulan',
                    '4 Campaign Marketing per Bulan',
                    'Desain Konten Premium & Custom',
                    'Content Strategy Lengkap',
                    'Campaign Planning & Execution',
                    'Advanced Audience Targeting',
                    'Influencer Collaboration (optional)',
                    'Real-time Monitoring',
                    'Comprehensive Monthly Report',
                    'Strategy Consultation',
                ]),
                'target_beneficiaries' => 4,
                'service_type' => 'Social Media Marketing',
                'is_active' => true,
                'is_featured' => true,
                'order' => 4,
            ],

            // PAKET BEASISWA S2 & S3
            [
                'name' => 'Paket Beasiswa Tabungan S2',
                'slug' => 'paket-beasiswa-tabungan-s2',
                'icon' => 'heroicon-o-chart-bar',
                'category' => 's2-s3',
                'price_min' => 4500000,
                'price_max' => 7000000,
                'description' => 'Business & Marketing Development untuk membantu mahasiswa melanjutkan pendidikan S2. Setiap proyek menjadi tabungan beasiswa bagi mahasiswa berprestasi.',
                'features' => json_encode([
                    'Business Strategy Consultation',
                    'Marketing Plan Development',
                    'Market Research & Analysis',
                    'Brand Positioning Strategy',
                    'Digital Marketing Strategy',
                    'Sales Funnel Optimization',
                    'Performance Metrics Setup',
                    'Monthly Consultation (3 bulan)',
                ]),
                'target_beneficiaries' => 1,
                'service_type' => 'Business & Marketing Development',
                'is_active' => true,
                'is_featured' => false,
                'order' => 5,
            ],
            [
                'name' => 'Paket Beasiswa Lanjutan S2',
                'slug' => 'paket-beasiswa-lanjutan-s2',
                'icon' => 'heroicon-o-academic-cap',
                'category' => 's2-s3',
                'price_min' => 5000000,
                'price_max' => 10000000,
                'description' => 'Coaching Clinic / Pelatihan Humas Kreatif dan Content Creator untuk pengembangan skill mahasiswa S2. Program ini langsung memberikan beasiswa pendidikan lanjutan.',
                'features' => json_encode([
                    'Coaching Clinic (6-8 sesi)',
                    'Pelatihan Humas Kreatif',
                    'Content Creator Training',
                    'Social Media Strategy',
                    'Personal Branding',
                    'Public Speaking',
                    'Writing Workshop',
                    'Portfolio Development',
                    'Certificate of Completion',
                    'Mentoring Program (3 bulan)',
                ]),
                'target_beneficiaries' => 1,
                'service_type' => 'Coaching Clinic',
                'is_active' => true,
                'is_featured' => false,
                'order' => 6,
            ],
            [
                'name' => 'Paket Beasiswa Tabungan S3',
                'slug' => 'paket-beasiswa-tabungan-s3',
                'icon' => 'heroicon-o-globe-alt',
                'category' => 's2-s3',
                'price_min' => 7000000,
                'price_max' => 20000000,
                'description' => 'Web Development/Web Management untuk mendukung pendidikan S3. Setiap website yang dikembangkan berkontribusi pada beasiswa pendidikan tingkat doktoral.',
                'features' => json_encode([
                    'Website Development',
                    'Custom Design & UI/UX',
                    'Responsive Design (Mobile & Desktop)',
                    'Content Management System',
                    'SEO Optimization',
                    'Security Features',
                    'Admin Panel',
                    'Database Integration',
                    'Hosting Setup & Configuration',
                    'Domain & SSL Certificate',
                    'Web Management (6 bulan)',
                    'Technical Support',
                ]),
                'target_beneficiaries' => 1,
                'service_type' => 'Web Development',
                'is_active' => true,
                'is_featured' => true,
                'order' => 7,
            ],
            [
                'name' => 'Paket Beasiswa Lanjutan S3',
                'slug' => 'paket-beasiswa-lanjutan-s3',
                'icon' => 'heroicon-o-device-phone-mobile',
                'category' => 's2-s3',
                'price_min' => 25000000,
                'price_max' => 50000000,
                'description' => 'App Development/App Management untuk memberikan beasiswa pendidikan S3. Proyek aplikasi mobile yang kompleks dengan dampak langsung pada pendidikan mahasiswa doktoral.',
                'features' => json_encode([
                    'Mobile App Development',
                    'Cross-Platform (Android & iOS) atau Native',
                    'Custom UI/UX Design',
                    'Backend API Development',
                    'Database Design & Implementation',
                    'User Authentication & Authorization',
                    'Push Notifications',
                    'Analytics Integration',
                    'Admin Dashboard',
                    'App Store/Play Store Deployment',
                    'App Management (6 bulan)',
                    'Technical Support & Updates',
                    'Documentation',
                ]),
                'target_beneficiaries' => 1,
                'service_type' => 'App Development',
                'is_active' => true,
                'is_featured' => true,
                'order' => 8,
            ],

            // MENABUNG INDONESIA EMAS
            [
                'name' => 'Menabung Indonesia Emas',
                'slug' => 'menabung-indonesia-emas',
                'icon' => 'heroicon-o-heart',
                'category' => 'donation',
                'price_min' => 0,
                'price_max' => 0,
                'description' => 'Donasi seikhlasnya untuk kebutuhan logistik, akomodasi dan program pengabdian kepada masyarakat. Mari berkontribusi dalam mewujudkan Indonesia Emas melalui pendidikan.',
                'features' => json_encode([
                    'Donasi Seikhlasnya',
                    'Untuk Kebutuhan Logistik Tim',
                    'Akomodasi Mahasiswa',
                    'Program Pengabdian Masyarakat',
                    'Pengembangan Komunitas',
                    'Kegiatan Sosial & Edukasi',
                    'Transparansi Laporan Donasi',
                    'Sertifikat Apresiasi Donatur',
                ]),
                'target_beneficiaries' => 0,
                'service_type' => 'Donasi',
                'is_active' => true,
                'is_featured' => false,
                'order' => 9,
            ],
        ];

        foreach ($packages as $package) {
            Package::updateOrCreate(
                ['slug' => $package['slug']],
                $package
            );
        }
    }
}
